- name: Ensure otel group exists
  ansible.builtin.group:
    name: "{{ otel_group }}"
    state: present

- name: Create otel user for running the OpenTelemetry Collector
  ansible.builtin.user:
    name: "{{ otel_user }}"
    state: present
    shell: /usr/sbin/nologin
    createhome: no
    system: yes
    groups: adm,systemd-journal,www-data,"{{ otel_group }}"

- name: Ensure otelcol log directory exists
  ansible.builtin.file:
    path: /var/log/otelcol
    state: directory
    owner: otel
    group: otel
    mode: '0755'

- name: Download OpenTelemetry deb
  get_url:
    url: "{{ opentel_url }}"
    dest: /tmp/otelcol-contrib_linux_arm64.deb
    mode: '0755'

- name: Install OpenTel package
  ansible.builtin.apt:
    deb: /tmp/otelcol-contrib_linux_arm64.deb

- name: Remove Otel installation files
  ansible.builtin.file:
    path: /tmp/otelcol-contrib_linux_arm64.deb
    state: absent

- name: Configure systemd configuration
  template:
    src: otelcol-contrib.service.j2
    dest: "{{ otel_service_path }}"
    mode: 0644

- name: Copy the OpenTel configuration file
  ansible.builtin.template:
    src: opentel-config.yaml.j2
    dest: /etc/{{ otel_service_name }}/opentel.yaml
    owner: otel
    group: otel
    mode: '0644'

- name: Restart service to pick up config
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes
    name: otelcol-contrib.service