- name: Ensure node_exporter group exists
  ansible.builtin.group:
    name: "{{ exporter_group }}"
    state: present

- name: Create node_exporter user
  ansible.builtin.user:
    name: "{{ exporter_user }}"
    state: present
    shell: /usr/sbin/nologin
    createhome: no
    system: yes
    groups: "{{ exporter_group }}"

- name: Download node_exporter
  get_url:
    url: "{{ exporter_url }}"
    dest: "/tmp/{{ exporter_url | basename }}"
    mode: '0755'

- name: Unpack node_exporter
  ansible.builtin.unarchive:
    src: "/tmp/{{ exporter_url | basename }}"
    dest: /tmp/

- name: Copy node_exporter to bin
  ansible.builtin.copy:
    src: "/tmp/{{ exporter_url | basename | regex_replace('\\.tar\\.gz$', '') }}/node_exporter"
    dest: /usr/local/bin
    owner: exporter
    group: exporter
    mode: '0755'

- name: Remove node_exporter installation files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/tmp/{{ exporter_url | basename }}"
    - "/tmp/{{ exporter_url | basename | regex_replace('\\.tar\\.gz$', '') }}"

- name: Configure node_exporter systemd configuration
  template:
    src: node_exporter.service.j2
    dest: "/etc/systemd/system/node_exporter.service"
    mode: 0644

- name: Restart node_exporter service
  ansible.builtin.systemd:
    enabled: true
    state: restarted
    daemon_reload: yes
    name: node_exporter.service